# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 2d122d33d2571d3306d0e75bbf2c234a4bb6218356cf396b1240429ffbc8c1c379e53a3b724e78cadc09e4cf664d80d28c24b71d9d5c121dc4a840964b026335

test:
  secret_key_base: b258b97dcc637cf390144bff8b592ef70e8e2d7431410805840033f1e3e2c81d24eec570b7f9b83e59813e36145cae8dbafe71307bff14266ef1eb3a2bc780f5

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
